Rename switch namespace
switch is a reserved keyword in C++.. Therefore "namespace switch" is
illegal C++ code.

Add a couple lines of python code to check for keywords and then rename
with a rf_ at the front, e.g. namespace rf_switch.

Rerun the script update_schemas.py script.

This showed downstream, but probably would have upstream too.

```
switch.hpp:8:11: error: expected identifier or '{' [clang-diagnostic-error]
    8 | namespace switch
      |           ^
.../bmcweb/redfish-core/include/generated/enums/switch.hpp:8:11: error: expected unqualified-id [clang-diagnostic-error]

...

FAILED: meson-internal__clang-tidy-fix
```

Change-Id: I58be67fc0df6e5056e63da5302724e6509b7114b
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>