nvidia_log_services: Remove inline from forward declarations
Change:
* Remove the inline keyword from createDump() and downloadDumpEntry()
  forward declarations.

Reason:
* These functions are defined in log_services.hpp, and inline forward
  declarations without definitions cause build failures.
Error message:
```
| ../git/redfish-core/lib/nvidia_log_services.hpp:1160:13: error: inline
function 'void redfish::createDump(const std::shared_ptr<bmcweb::
AsyncResp>&, const crow::Request&, const std::string&)' used but never
defined [-Werror]
|  1160 | inline void createDump(const std::shared_ptr<bmcweb::AsyncResp
>& asyncResp,
|       |             ^~~~~~~~~~
| ../git/redfish-core/lib/nvidia_log_services.hpp:1162:13: error: inline
function 'void redfish::downloadDumpEntry(const std::shared_ptr<bmcweb
::AsyncResp>&, const std::string&, const std::string&)' used but never
defined [-Werror]
|  1162 | inline void downloadDumpEntry(
|       |             ^~~~~~~~~~~~~~~~~
```

Fixes nvbug https://

Signed-off-by: Amy Chang <yahanc@nvidia.com>